defaults: &defaults
  app:
    title: Crossfit Red Shell Чебоксары — аффилированный клуб кроссфита
    meta_title: Кроссфит CrossFit Red Shell
    meta_description: Кроссфит в Чебоксарах. Аффилированный клуб. Просторный зал, сертифицированные тренера, профессиональное оборудование. Тренировки, соревнования, программы.

development:
  <<: *defaults


test:
  <<: *defaults


production:
  <<: *defaults


staging:
  <<: *defaults
