defaults: &defaults
  app:
    title: CrossFit Red Shell Чебоксары — аффилированный клуб кроссфита
    share_title: CrossFit Red Shell Чебоксары
    share_description: аффилированный клуб CrossFit
    meta_title: КроссФит CrossFit Red Shell
    meta_description: Кроссфит в Чебоксарах. Аффилированный клуб. Просторный зал, сертифицированные тренера, профессиональное оборудование. Тренировки, соревнования, программы.
    phone: (8352) 38-47-17
    phone_tel: +78352384717
    admin_email: admin@crossfitredshell.com

    asset_host: http://crossfitredshell.com

    default_url_options: &default_url_options
      host: HOSTNAME
      port: 80

  mailer_defaults: &mailer_defaults
    from: 'mailer@crossfitredshell.com'
    host: crossfitredshell.com

    default_url_options: &default_url_options
      host: HOSTNAME
      port: 80

  action_mailer: &action_mailer
    raise_delivery_errors: false
    default_url_options:
      <<: *default_url_options

development:
  <<: *defaults
  action_mailer:
    <<: *action_mailer
    delivery_method: :smtp
    smtp_settings:
      address: localhost
      port: 1025   # mailcatcher
    raise_delivery_errors: true

test:
  <<: *defaults
  capybara:
    port: 57500

  mailer_defaults:
    <<: *mailer_defaults

  action_mailer:
    <<: *action_mailer
    delivery_method: :test

production:
  <<: *defaults
  mailer_defaults:
    <<: *mailer_defaults
  action_mailer: &action_mailer
    raise_delivery_errors: false
    default_url_options:
      <<: *default_url_options
    smtp_settings:
      address: "localhost"
      port: 25
      domain: crossfitredshell.com
      enable_starttls_auto: false

staging:
  <<: *defaults
  mailer_defaults:
    <<: *mailer_defaults

