defaults: &defaults
  app:
    title: Crossfit Red Shell Чебоксары — аффилированный клуб кроссфита

development:
  <<: *defaults


test:
  <<: *defaults


production:
  <<: *defaults


staging:
  <<: *defaults
